name: Snaplet Capture

author: Snaplet

description: Use snaplet to capture a snapshot of your database

inputs:
  destination-path:
    description: The path to where the snapshots are stored
    required: false
    type: string
  tags:
    description: Attach tags to the snapshot (seperate by comma)
    required: false
    type: string
  skip-share:
    description: Skip the share step
    required: false
    type: boolean
    default: true

runs:
  using: composite
  steps:
    - name: Install Snaplet CLI
      shell: bash
      run: curl -sS "https://app.snaplet.dev/get-cli/" | bash &> "/dev/null"
    - name: Install postgres 15
      shell: bash
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
        sudo apt update
        sudo apt-get install postgresql-client-15 -y
        sudo pg_dropcluster 14 main --stop
    - name: Capture a snapshot
      shell: bash
      run: |
        if [[ -n "${inputs.tags}" ]]; then
          snaplet snapshot capture "${{ inputs.destination-path }}" --tags "${{ inputs.tags }}"
        else
          snaplet snapshot capture "${{ inputs.destination-path }}"
        fi
    - name: Share snapshot
      if: ${{ inputs.skip-share == false }}
      shell: bash
      run: snaplet snapshot share --latest
